server:
  port: 8080

spring:
  application:
    name: bookService
  datasource:
    url: jdbc:mysql://localhost:3306/bm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
